// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitePenacova.Infrastructure.Data;

#nullable disable

namespace VisitePenacova.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240501173744_SeedLocalToDb")]
    partial class SeedLocalToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitePenacova.Domain.Entities.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Freguesia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Praias fluviais",
                            Descricao = "Praia fluvial com bandeira azul",
                            Freguesia = "São Pedro de Alva",
                            ImageUrl = "https://placehold.co/600x400",
                            Localidade = "Vimieiro",
                            Nome = "Vimieiro"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Monumentos históricos",
                            Descricao = "Monumento do século VI D.C",
                            Freguesia = "Lorvão",
                            ImageUrl = "https://placehold.co/600x401",
                            Localidade = "Lorvão",
                            Nome = "Mosteiro de Lorvão"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Cascatas",
                            Descricao = "Cascata com pequena lagoa",
                            Freguesia = "Figueira de Lorvão",
                            ImageUrl = "https://placehold.co/600x402",
                            Localidade = "Mata do Maxial",
                            Nome = "Poço Grande"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
