// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VisitePenacova.Infrastructure.Data;

#nullable disable

namespace VisitePenacova.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VisitePenacova.Domain.Entities.ComentNum", b =>
                {
                    b.Property<int>("Coment_Num")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.HasKey("Coment_Num");

                    b.HasIndex("LocalId");

                    b.ToTable("ComentNums");

                    b.HasData(
                        new
                        {
                            Coment_Num = 10,
                            Comentario = "Praia bastante limpa. Irei voltar certamente!",
                            LocalId = 1
                        },
                        new
                        {
                            Coment_Num = 11,
                            Comentario = "Água gelada!",
                            LocalId = 1
                        },
                        new
                        {
                            Coment_Num = 12,
                            Comentario = "Melhor praia flúvial do pais!",
                            LocalId = 1
                        },
                        new
                        {
                            Coment_Num = 13,
                            Comentario = "Praia com bandeira azul.",
                            LocalId = 1
                        },
                        new
                        {
                            Coment_Num = 21,
                            Comentario = "Um pedaço de história",
                            LocalId = 2
                        },
                        new
                        {
                            Coment_Num = 22,
                            Comentario = "Que órgão!",
                            LocalId = 2
                        },
                        new
                        {
                            Coment_Num = 23,
                            Comentario = "Vale a pena a visita!",
                            LocalId = 2
                        },
                        new
                        {
                            Coment_Num = 30,
                            Comentario = "Como é que isto existe?",
                            LocalId = 3
                        },
                        new
                        {
                            Coment_Num = 31,
                            Comentario = "Que dia bem passado! Já só penso em voltar!",
                            LocalId = 3
                        });
                });

            modelBuilder.Entity("VisitePenacova.Domain.Entities.Local", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Freguesia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Locais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Praias fluviais",
                            Descricao = "Praia fluvial com bandeira azul",
                            Freguesia = "São Pedro de Alva",
                            ImageUrl = "https://placehold.co/600x400",
                            Localidade = "Vimieiro",
                            Nome = "Vimieiro"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Monumentos históricos",
                            Descricao = "Monumento do século VI D.C",
                            Freguesia = "Lorvão",
                            ImageUrl = "https://placehold.co/600x401",
                            Localidade = "Lorvão",
                            Nome = "Mosteiro de Lorvão"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Cascatas",
                            Descricao = "Cascata com pequena lagoa",
                            Freguesia = "Figueira de Lorvão",
                            ImageUrl = "https://placehold.co/600x402",
                            Localidade = "Mata do Maxial",
                            Nome = "Poço Grande"
                        });
                });

            modelBuilder.Entity("VisitePenacova.Domain.Entities.ComentNum", b =>
                {
                    b.HasOne("VisitePenacova.Domain.Entities.Local", "Local")
                        .WithMany()
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Local");
                });
#pragma warning restore 612, 618
        }
    }
}
